apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: pvc-test
spec:
  crVersion: 1.14.0
  secretsName: pvc-test
  allowUnsafeConfigurations: false
  upgradeOptions:
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
  haproxy:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.14.0-haproxy
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.14.0-logcollector
