apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-tst-pxc-pxc-0
spec:
  dataSource:
    name: datadir-tst-pxc-pxc-0-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-tst-pxc-pxc-1
spec:
  dataSource:
    name: datadir-tst-pxc-pxc-1-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-tst-pxc-pxc-2
spec:
  dataSource:
    name: datadir-tst-pxc-pxc-2-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
