apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: percona-pxc-rbac
    namespace: prod-dbs
rules:
    - apiGroups: ["pxc.percona.com"]
      resources: ["*"]
      verbs: ["*"]
    - apiGroups: [""]
      resources:
      - pods
      - pods/exec
      - pods/log
      - configmaps
      - services
      - persistentvolumeclaims
      - secrets
      verbs:
      - get
      - list
      - watch
