apiVersion: pg.percona.com/v2beta1
kind: PerconaPGCluster
metadata:
  name: cluster1
spec:

  image: percona/percona-postgresql-operator:2.0.0-ppg14-postgres
  imagePullPolicy: Always
  postgresVersion: 14

  instances:
  - name: instance1
    replicas: 2
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  proxy:
    pgBouncer:
#      replicas: 3
      image: percona/percona-postgresql-operator:2.0.0-ppg14-pgbouncer

  backups:
    pgbackrest:
      image: percona/percona-postgresql-operator:2.0.0-ppg14-pgbackrest
      manual:
        repoName: repo1
        options:
         - --type=full
      repos:
      - name: repo1
        schedules:
          full: "0 0 * * 6"
#          differential: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  pmm:
    enabled: false
    image: percona/pmm-client:2.32.0
    secret: cluster1-pmm-secret
    serverHost: monitoring-service
