apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.15.0
    chart: psmdb-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: percona-mongo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
