apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secrets
type: Opaque
stringData:
  root: root_password
  xtrabackup: backup_password
  monitor: monitor_password
  clustercheck: clustercheck_password
  pmmserver: mg;N96km)vKN7Q-1
  operator: operator_password
  replication: replication_password
  orchestrator: orchestrator_password
